name: Deployment Exercise 1
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code (checkout)
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deployment..."